module.exports.keyMapping = {
 controller: {
LT: "low",
LB: "flat",
RB: "sharp",
RT: "high",
L: "do",
U: "re",
R: "mi",
D: "fa",
X: "so",
Y: "la",
B: "si",
A: "dd",
},
keyboard: {
dd: {key: "i", code: "KeyI"},
dd_: {key: "", code: ""},
do: {key: "q", code: "KeyQ"},
doS: {key: "2", code: "Digit2"},
doS_: {key: "", code: ""},
fa: {key: "r", code: "KeyR"},
faS: {key: "5", code: "Digit5"},
faS_: {key: "", code: ""},
fa_: {key: "", code: ""},
flat: {key: "", code: ""},
high: {key: "Ctrl", code: "ControlLeft"},
la: {key: "y", code: "KeyY"},
laS: {key: "7", code: "Digit7"},
laS_: {key: "", code: ""},
la_: {key: "", code: ""},
low: {key: "Shift", code: "ShiftLeft"},
mi: {key: "e", code: "KeyE"},
mi_: {key: "", code: ""},
re: {key: "w", code: "KeyW"},
reS: {key: "3", code: "Digit3"},
reS_: {key: "", code: ""},
re_: {key: "", code: ""},
sharp: {key: "", code: ""},
si: {key: "u", code: "KeyU"},
si_: {key: "", code: ""},
so: {key: "t", code: "KeyT"},
soS: {key: "6", code: "Digit6"},
soS_: {key: "", code: ""},
so_: {key: "", code: ""},
_do: {key: "z", code: "KeyZ"},
_doS: {key: "", code: ""},
_fa: {key: "v", code: "KeyV"},
_faS: {key: "", code: ""},
_la: {key: "n", code: "KeyN"},
_laS: {key: "", code: ""},
_mi: {key: "c", code: "KeyC"},
_re: {key: "x", code: "KeyX"},
_reS: {key: "", code: ""},
_si: {key: "m", code: "KeyM"},
_so: {key: "b", code: "KeyB"},
_soS: {key: "", code: ""},
}};